Switched rubygems.org to http
In order to be able tu use bundle install on SLE 11 within an
development environment we are forced to switch to http because the
usage of the https url results in an error:

NoMethodError: undefined method `extensions' for nil:NilClass